#################################
#           Backend             #
#################################
# GLX backend kullanarak daha yüksek GPU performansı elde edin
backend = "glx";

#################################
#            VSync              #
#################################
# VSync (Dikey Senkronizasyon) kapatma
vsync = true;

#################################
#           Opacity             #
#################################
# Genel opaklık kuralları
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

# st (simple terminal) penceresi için arka plan saydamlığı ekleme
# 'st' veya 'st-256color' gibi sınıf isimlerini hedef alır.
# 0.85 değeri %85 opaklık (%15 şeffaflık) sağlar.
opacity-rule = [
  "85:class_g = 'st'",
  "85:class_g = 'st-256color'",
  "85:class_g = 'Alacritty'",
  "85:class_g = 'XTerm'"
];

shadow-exclude = [
  "class_g = 'Polybar'"
];

#################################
#     GLX Backend İnce Ayar     #
#################################
# glx backend kullanılırken yırtılmaları önlemek ve performansı artırmak için ek ayarlar
use-damage = true;
## Shadow
shadow = true;
shadow-radius = 12;
shadow-offset-x = -17;
shadow-offset-y = -7;
shadow-opacity = 0.5;

